### ISSUE TITLE
In which part can I turn this into a version using openai chatgpt api?

### ISSUE THREAD

**Issue by ShuYuHuang** [huggingface/huggingface-vscode#12]
As title, I want to build an auto-complete extension for coding, and I want to use my OpenAI API for completion with ChatGPT. Which part in this repo should I dig into first?

**Comment by mishig25** [comment]
you can change [this fetch request](https://github.com/huggingface/tabnine-vscode/blob/ef44e917deac46410d30319925fd2b527b3c0a96/src/runCompletion.ts#L88-L92)
