### ISSUE TITLE
How to authenticate?

### ISSUE THREAD

**Issue by DavidArenburg** [huggingface/huggingface-vscode#15]
Hello, 
You are saying [here](https://github.com/huggingface/huggingface-vscode#hf-api-token) "*You can supply your HF API token ([hf.co/settings/token](https://hf.co/settings/token)) with this command:*" but you literally not providing any command.
I've installed the extension, I've generated the token, but I have not the slightest idea where to insert it. 
How do I get to that window where "Hugging Face Code: Set API token" appears?
Thank you

**Comment by mishig25** [comment]
Hello @DavidArenburg 

Provided more details in the description: 6158e52cca46ce31b595a68c5cf391be71a73cbe
