### ISSUE TITLE
Error to set up API Key GBUS Related

### ISSUE THREAD

**Issue by TheoOliveira** [huggingface/huggingface-vscode#17]
![Captura de tela_2023-05-07_21-11-52](https://user-images.githubusercontent.com/11945175/236709859-06b9ae7b-4af7-4f35-9666-91a90159519f.png)

System: Nixos 22.04
DE: i3 + xfce4
vscode version: 1.73.1

I've tried to use it but it gives this error so it's unusable at this point at least for me.

**Comment by ADozois** [comment]
I faced the same problem and found this GitHub issue https://github.com/microsoft/vscode-docker/issues/1515 which pointed me in the correct direction. I didn't have any software to store my secrets and the extension had
nowhere to store the token. After I installed gnome-keyring I was able to use the extension. You need to install a software to store credentials, like gnome-keyring.

**Comment by TheoOliveira** [comment]
> I faced the same problem and found this GitHub issue [microsoft/vscode-docker#1515](https://github.com/microsoft/vscode-docker/issues/1515) which pointed me in the correct direction. I didn't have any software to store my secrets and the extension had nowhere to store the token. After I installed gnome-keyring I was able to use the extension. You need to install a software to store credentials, like gnome-keyring.

Hey bro, going to try this and let you know. Thanks!

**Comment by TheoOliveira** [comment]
The idea from @ADozois worked! Thanks bud!
