### ISSUE TITLE
HuggingFaceCode::setApiToken not found

### ISSUE THREAD

**Issue by harm-devries** [huggingface/huggingface-vscode#20]
I'm getting the following error when trying to set my HF API token:
<img width="600" alt="Screenshot 2023-05-08 at 15 52 27" src="https://user-images.githubusercontent.com/8825215/236842658-283b5a13-b4ed-40a3-8ee0-e81744ef422f.png">

```
Version: 1.78.0 (Universal)
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:11:00.813Z (4 days ago)
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.4.0
Sandboxed: No```

**Comment by ankushu** [comment]
I am getting the same issue. 
Version: 1.78.0 (Universal)
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:11:00.813Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.4.0
Sandboxed: Yes

Machine OS: Mac 13.3.1 (a)
Machine Processor: (22E772610a) 2.6 GHz 6-Core Intel Core i7

**Comment by ankushu** [comment]
@harm-devries It got resolved after I disable tab-nine.

**Comment by mishig25** [comment]
@ankushu oh I see. Thanks so much for finding the fix. Since it was forked from tabnine and I didn't fully change all the configs, there might be some kind of "clash of configs" going on? I will look further into it
