### ISSUE TITLE
Fill-in-the-Middle (FIM) Mode not working

### ISSUE THREAD

**Issue by atanida** [huggingface/huggingface-vscode#23]
Hello,

Thank you so much for this awesome open source alternative!

I am having an issue with the FIM option of Starcoder. "Is Fill Mode" box is ticked but the Hugging Face Code Output Console only shows/sends to the API the upper half of the code, no matter where I set the cursor. I press enter in the middle of the code but only the upper part is sent.

I am using a custom local endpoint: http://127.0.0.1:4000/ 

VSCode version:
Version: 1.78.0 (user setup)
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:09:00.748Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

Many thanks,

**Comment by mishig25** [comment]
I'm on it 👀

**Comment by mishig25** [comment]
Closed by https://github.com/huggingface/huggingface-vscode/pull/25
