### ISSUE TITLE
Support different languages than python (like TypeScript)

### ISSUE THREAD

**Issue by nirtamir2** [huggingface/huggingface-vscode#30]
Thanks for creating this extension!
I tried it with Python like the example in the README - and it auto-completes the code as expected.
[StartCoder](https://huggingface.co/bigcode/starcoder) supports 80+ languages - including TypeScript.
Even the [playground](https://huggingface.co/spaces/bigcode/bigcode-playground) allows me to complete TypeScript code.
So it will be nice to add support to those languages in the VSCode extension - which only worked for me in Python.
Thanks!

**Comment by PrestigeDevop** [comment]
thought this fine tuned to python I was able to get some suggestion if I use prompts like "in JS" it should have contextual knowledge like using the file format to decide which language or build the file projects as code dom to give overall knowledge

**Comment by JusttCallMeMike** [comment]
this issue seems pretty fresh, so I don't know what going one since it is working great for me with typescript 🤷‍♂️
