### ISSUE TITLE
Checking if the generated code is in The Stack shortcut not working

### ISSUE THREAD

**Issue by i-maslowski** [huggingface/huggingface-vscode#41]
Hi, 
I have done testing of the extension installation steps and then tried **Cmd+shift+a** shortcut. It didn't work. I changed system boundings for this shortcut, but it does nothing anyway.
Have I missed something?

**Comment by McPatate** [comment]
Can you provide steps to reproduce your error?

The extension is being refactored, I've tested the attribution check in the unreleased `0.0.39` and it seems to work.

**Comment by McPatate** [comment]
`0.1.0` is released, let me know if your issue is fixed
